use [$(DBName)]
go

--Entity
set identity_insert Entity on
insert into Entity(EID, CName, EName) values(1, 'WEB資源', 'URL')	         -- EID = 1
insert into Entity(EID, CName, EName) values(2, '會員', 'Member')	         -- EID = 2
insert into Entity(EID, CName, EName) values(3, '檔案', 'Archive')	     -- EID = 3
insert into Entity(EID, CName, EName) values(4, '公告', 'Announce')	     -- EID = 4
insert into Entity(EID, CName, EName) values(5, '貼文', 'Post')            -- EID = 5
set identity_insert Entity off
go

--URLScheme
insert into URLScheme values('http', 'HyperText Transfer Protocol')
insert into URLScheme values('https', 'HyperText Transfer Protocol')
go

--Status
insert into StatusCode(Status, Msg, CDes) values(-1, 'no text' ,'還未抓取網頁/沒有文件')
insert into StatusCode values(0, 'MD5 Redundant', NULL)
insert into StatusCode values(200, 'OK', '用於HTTP成功狀態')
insert into StatusCode values(400, 'Bad Request', 'HTTP')
insert into StatusCode values(401, 'Unauthorized', 'HTTP: Need Account/Passwor')
insert into StatusCode values(403, 'Forbidden', 'HTTP: Bad user, can not be browsed')
insert into StatusCode values(404, 'Not Found', NULL)
go

insert into ContentType values('text/html', 'HTML content type')
go

--Groups
set identity_insert Groups ON
insert into Groups(GID, GName, GDes, Status, Type) values(0, 'Administrators', 'System Administrator Group', 1, 0)
insert into Groups(GID, GName, GDes, Status, Type) values(1, 'Guests', 'System Gest Group', 1, 0)
insert into Groups(GID, GName, GDes, Status, Type) values(2, 'Users', 'System User Group', 1, 0)
set identity_insert Groups OFF
go

--Class
set identity_insert Class ON
insert into Class(cid, CName, EName, IDPath, NamePath, Type, LastModifiedDT, nObject, nLevel, imgID) values(0, '首頁', 'Home', '0', '首頁', 1, getdate(), 0, 0, 0)
--set class permission
insert into permission (cid, roletype, roleid, permissionbits) values (0, 0, 0, 127)
insert into permission (cid, roletype, roleid, permissionbits) values (0, 0, 1, 3)
insert into permission (cid, roletype, roleid, permissionbits) values (0, 0, 2, 3)
set identity_insert Class OFF
go

-- Create System Management Interface using default administrator account
declare @CCID int

exec dbo.xp_insertClass 0, 1, '系統管理', 'Management', @CCID output

delete from Permission where CID = @CCID
insert into Permission(CID, RoleType, RoleID, PermissionBits) values(@CCID, 0, 0, 127)
insert into Permission(CID, RoleType, RoleID, PermissionBits) values(@CCID, 0, 1, 0)
insert into Permission(CID, RoleType, RoleID, PermissionBits) values(@CCID, 0, 2, 0)
-- insert into Permission(CID, RoleType, RoleID, PermissionBits) values(@CCID, 1, 1, 127)

--Member
alter Table Object Drop Constraint FK_Object_OwnerMID
alter Table Member Drop Constraint FK_Member_MID
set identity_insert Object ON
insert Object(OID, Type, CName) Select 0, EID, 'Guest' From Entity Where EName = 'Member'
declare @id int
set @id = @@identity
set identity_insert Object OFF
insert Member(MID, Account, PWD, Valid, Status) Values(@id, 'Guest', '', 1, 1)
insert into GM (GID, MID, role, type, status) values (1, @id, 1, 1, 1)

insert Object(Type, CName) Select EID,'$(AdminName)' From Entity Where EName='Member'
set @id = @@identity
insert Member(MID, Account, PWD, Valid, Status) Select @id, '$(AdminName)', dbo.fn_getMD5Encode('$(AdminPWD)'), 1, 1
insert into GM (GID, MID, role, type, status) values (0, @id, 1, 1, 1)
alter Table Object Add Constraint FK_Object_OwnerMID Foreign Key(OwnerMID) References Member(MID)
alter Table Member Add Constraint FK_Member_MID Foreign Key(MID) References Object(OID)
go

--Nation
insert into Nation(CountryCode, CName, EName) values('AD', '安道爾', 'ANDORRA')
insert into Nation(CountryCode, CName, EName) values('AE', '阿拉伯聯合大公國', 'UNITED ARAB EMI')
insert into Nation(CountryCode, CName, EName) values('AF', '阿富汗', 'AFGHANISTAN')
insert into Nation(CountryCode, CName, EName) values('AG', '安地卡', 'ANTIGUA')
insert into Nation(CountryCode, CName, EName) values('AI', '安圭拉', 'ANGUILLA')
insert into Nation(CountryCode, CName, EName) values('AL', '阿爾巴尼亞', 'ALBANIA')
insert into Nation(CountryCode, CName, EName) values('AM', '亞美尼亞', 'ARMENIA')
insert into Nation(CountryCode, CName, EName) values('AN', '荷屬安地列斯', 'NETHERLANDS AN')
insert into Nation(CountryCode, CName, EName) values('AO', '安哥拉', 'ANGOLA')
insert into Nation(CountryCode, CName, EName) values('AQ', '南極洲', 'ANTARCTICA')
insert into Nation(CountryCode, CName, EName) values('AR', '阿根廷', 'ARGENTINA')
insert into Nation(CountryCode, CName, EName) values('AS', '美屬薩摩亞', 'AMERICAN SAMOA')
insert into Nation(CountryCode, CName, EName) values('AT', '奧地利', 'AUSTRIA')
insert into Nation(CountryCode, CName, EName) values('AU', '澳洲', 'AUSTRALIA')
insert into Nation(CountryCode, CName, EName) values('AW', '阿魯巴', 'ARUBA')
insert into Nation(CountryCode, CName, EName) values('AZ', '亞塞拜然', 'AZERBAIJAN')
insert into Nation(CountryCode, CName, EName) values('BA', '波士尼亞', 'BOSNIA HERZEGOVINA')
insert into Nation(CountryCode, CName, EName) values('BB', '巴巴多斯', 'BARBADOS')
insert into Nation(CountryCode, CName, EName) values('BC', '歐盟', 'EUROPEAN UNION')
insert into Nation(CountryCode, CName, EName) values('BD', '孟加拉', 'BANGLADESH')
insert into Nation(CountryCode, CName, EName) values('BE', '比利時', 'BELGIUM')
insert into Nation(CountryCode, CName, EName) values('BF', '布吉納法索', 'BURKINA FASO')
insert into Nation(CountryCode, CName, EName) values('BG', '保加利亞', 'BULGARIA')
insert into Nation(CountryCode, CName, EName) values('BH', '巴林', 'BAHRAIN')
insert into Nation(CountryCode, CName, EName) values('BI', '浦隆地', 'BURUNDI')
insert into Nation(CountryCode, CName, EName) values('BJ', '貝寧', 'BENIN')
insert into Nation(CountryCode, CName, EName) values('BM', '百慕達', 'BERMUDA')
insert into Nation(CountryCode, CName, EName) values('BN', '汶萊', 'BRUNEI')
insert into Nation(CountryCode, CName, EName) values('BO', '玻利維亞', 'BOLIVIA')
insert into Nation(CountryCode, CName, EName) values('BR', '巴西', 'BRAZIL')
insert into Nation(CountryCode, CName, EName) values('BS', '巴哈馬', 'BAHAMAS')
insert into Nation(CountryCode, CName, EName) values('BT', '不丹', 'BHUTAN')
insert into Nation(CountryCode, CName, EName) values('BV', '波維特島', 'BOUVET ISLAND')
insert into Nation(CountryCode, CName, EName) values('BW', '波札那', 'BOTSWANA')
insert into Nation(CountryCode, CName, EName) values('BY', '白俄羅斯', 'BELARUS')
insert into Nation(CountryCode, CName, EName) values('BZ', '貝里斯', 'BELIZE')
insert into Nation(CountryCode, CName, EName) values('CA', '加拿大', 'CANADA')
insert into Nation(CountryCode, CName, EName) values('CC', '可可斯群島', 'COCOS ISLANDS')
insert into Nation(CountryCode, CName, EName) values('CD', '剛果民主共和國', 'CONGO DEM REP')
insert into Nation(CountryCode, CName, EName) values('CF', '中非', 'CENTRAL AFRICA')
insert into Nation(CountryCode, CName, EName) values('CG', '剛果共和國', 'CONGO REPUBLIC')
insert into Nation(CountryCode, CName, EName) values('CH', '瑞士', 'SWITZERLAND')
insert into Nation(CountryCode, CName, EName) values('CI', '象牙海岸', 'IVORY COAST')
insert into Nation(CountryCode, CName, EName) values('CK', '科克群島', 'COOK ISLANDS')
insert into Nation(CountryCode, CName, EName) values('CL', '智利', 'CHILE')
insert into Nation(CountryCode, CName, EName) values('CM', '喀麥隆', 'CAMEROON')
insert into Nation(CountryCode, CName, EName) values('CN', '中國', 'CHINA')
insert into Nation(CountryCode, CName, EName) values('CO', '哥倫比亞', 'COLOMBIA')
insert into Nation(CountryCode, CName, EName) values('CR', '哥斯達黎加', 'COSTA RICA')
insert into Nation(CountryCode, CName, EName) values('CS', '以色列謝客爾', 'ISRAEL SHEKEL')
insert into Nation(CountryCode, CName, EName) values('CT', '坎頓與恩德伯里島', 'CANTON AND ENDERBURY IS')
insert into Nation(CountryCode, CName, EName) values('CU', '古巴', 'CUBA')
insert into Nation(CountryCode, CName, EName) values('CV', '維德角島', 'CAPE VERDE')
insert into Nation(CountryCode, CName, EName) values('CX', '聖誕島', 'CHRISTMAS IS')
insert into Nation(CountryCode, CName, EName) values('CY', '塞普勒斯', 'CYPRUS')
insert into Nation(CountryCode, CName, EName) values('CZ', '捷克', 'CZECH REPUBLIC')
insert into Nation(CountryCode, CName, EName) values('DD', '東德', 'EAST GERMANY')
insert into Nation(CountryCode, CName, EName) values('DE', '德國', 'GERMANY')
insert into Nation(CountryCode, CName, EName) values('DJ', '吉布地', 'DJIBOUTI')
insert into Nation(CountryCode, CName, EName) values('DK', '丹麥', 'DENMARK')
insert into Nation(CountryCode, CName, EName) values('DM', '多米尼克', 'DOMINICA')
insert into Nation(CountryCode, CName, EName) values('DO', '多明尼加', 'DOMINICAN REP')
insert into Nation(CountryCode, CName, EName) values('DP', '剛果民主共和國', 'CONGO DEM REP')
insert into Nation(CountryCode, CName, EName) values('DZ', '阿爾及利亞', 'ALGERIA')
insert into Nation(CountryCode, CName, EName) values('EC', '厄瓜多', 'ECUADOR')
insert into Nation(CountryCode, CName, EName) values('EE', '愛沙尼亞', 'ESTONIA')
insert into Nation(CountryCode, CName, EName) values('EG', '埃及', 'EGYPT')
insert into Nation(CountryCode, CName, EName) values('EH', '西撒哈拉', 'WESTERN SAHARA')
insert into Nation(CountryCode, CName, EName) values('ER', '厄利垂亞', 'ERITREA')
insert into Nation(CountryCode, CName, EName) values('ES', '西班牙', 'SPAIN')
insert into Nation(CountryCode, CName, EName) values('ET', '依索比亞', 'ETHIOPIA')
insert into Nation(CountryCode, CName, EName) values('FI', '芬蘭', 'FINLAND')
insert into Nation(CountryCode, CName, EName) values('FJ', '斐濟群島', 'FIJI')
insert into Nation(CountryCode, CName, EName) values('FK', '福克蘭群島', 'FALKLAND ISLANDS')
insert into Nation(CountryCode, CName, EName) values('FM', '密克羅尼西亞', 'MICRONESIA')
insert into Nation(CountryCode, CName, EName) values('FO', '法羅群島', 'FAROE ISLANDS')
insert into Nation(CountryCode, CName, EName) values('FR', '法國', 'FRANCE')
insert into Nation(CountryCode, CName, EName) values('GA', '加蓬', 'GABON')
insert into Nation(CountryCode, CName, EName) values('GB', '英國', 'UNITED KINGDOM')
insert into Nation(CountryCode, CName, EName) values('GD', '格林納達', 'GRENADA')
insert into Nation(CountryCode, CName, EName) values('GE', '喬治亞', 'GEORGIA')
insert into Nation(CountryCode, CName, EName) values('GF', '法屬圭亞那', 'FRENCH GUIANA')
insert into Nation(CountryCode, CName, EName) values('GH', '迦納', 'GHANA')
insert into Nation(CountryCode, CName, EName) values('GI', '直布羅陀', 'GIBRALTAR')
insert into Nation(CountryCode, CName, EName) values('GL', '格林蘭', 'GREENLAND')
insert into Nation(CountryCode, CName, EName) values('GM', '甘比亞', 'GAMBIA')
insert into Nation(CountryCode, CName, EName) values('GN', '幾內亞', 'GUINEA')
insert into Nation(CountryCode, CName, EName) values('GP', '瓜德魯普島', 'GUADELOUPE')
insert into Nation(CountryCode, CName, EName) values('GQ', '赤道幾內亞', 'EQUATORIAL GUIN')
insert into Nation(CountryCode, CName, EName) values('GR', '希臘', 'GREECE')
insert into Nation(CountryCode, CName, EName) values('GS', '南喬治亞與南桑威奇', 'SOUTH GEORGIA & SOUTH SANDWICH ISLANDS')
insert into Nation(CountryCode, CName, EName) values('GT', '瓜地馬拉', 'GUATEMALA')
insert into Nation(CountryCode, CName, EName) values('GU', '關島', 'GUAM')
insert into Nation(CountryCode, CName, EName) values('GW', '幾內亞比索', 'GUINEA BISSAU')
insert into Nation(CountryCode, CName, EName) values('GY', '蓋亞那', 'GUYANA')
insert into Nation(CountryCode, CName, EName) values('HK', '香港', 'HONG KONG')
insert into Nation(CountryCode, CName, EName) values('HM', '赫德及麥當勞群島', 'HEARD MACDONALD IS')
insert into Nation(CountryCode, CName, EName) values('HN', '洪都拉斯', 'HONDURAS')
insert into Nation(CountryCode, CName, EName) values('HR', '克羅埃西亞', 'CROATIA')
insert into Nation(CountryCode, CName, EName) values('HT', '海地', 'HAITI')
insert into Nation(CountryCode, CName, EName) values('HU', '匈牙利', 'HUNGARY')
insert into Nation(CountryCode, CName, EName) values('ID', '印尼', 'INDONESIA')
insert into Nation(CountryCode, CName, EName) values('IE', '愛爾蘭', 'IRELAND')
insert into Nation(CountryCode, CName, EName) values('IL', '以色列', 'ISRAEL')
insert into Nation(CountryCode, CName, EName) values('IN', '印度', 'INDIA')
insert into Nation(CountryCode, CName, EName) values('IO', '英屬印度洋', 'BRITISH INDIAN OCEAN')
insert into Nation(CountryCode, CName, EName) values('IQ', '伊拉克', 'IRAQ')
insert into Nation(CountryCode, CName, EName) values('IR', '伊朗', 'IRAN')
insert into Nation(CountryCode, CName, EName) values('IS', '冰島', 'ICELAND')
insert into Nation(CountryCode, CName, EName) values('IT', '意大利', 'ITALY')
insert into Nation(CountryCode, CName, EName) values('JM', '牙買加', 'JAMAICA')
insert into Nation(CountryCode, CName, EName) values('JO', '約旦', 'JORDAN')
insert into Nation(CountryCode, CName, EName) values('JP', '日本', 'JAPAN')
insert into Nation(CountryCode, CName, EName) values('JT', '約翰遜島', 'JOHNSON ISLAND')
insert into Nation(CountryCode, CName, EName) values('KE', '肯尼亞', 'KENYA')
insert into Nation(CountryCode, CName, EName) values('KG', '吉爾吉斯', 'KYRGYZSTAN')
insert into Nation(CountryCode, CName, EName) values('KH', '柬埔寨', 'CAMBODIA')
insert into Nation(CountryCode, CName, EName) values('KI', '吉里巴斯', 'KIRIBATI')
insert into Nation(CountryCode, CName, EName) values('KM', '科摩羅', 'COMOROS')
insert into Nation(CountryCode, CName, EName) values('KN', '尼維斯', 'ST KITTS-NEVIS')
insert into Nation(CountryCode, CName, EName) values('KP', '北韓', 'NORTH KOREA')
insert into Nation(CountryCode, CName, EName) values('KR', '韓國', 'SOUTH KOREA')
insert into Nation(CountryCode, CName, EName) values('KW', '科威特', 'KUWAIT')
insert into Nation(CountryCode, CName, EName) values('KY', '開曼群島', 'CAYMAN ISLANDS')
insert into Nation(CountryCode, CName, EName) values('KZ', '哈薩克', 'KAZAKHSTAN')
insert into Nation(CountryCode, CName, EName) values('LA', '寮國', 'LAO PEOPLES DEM REP')
insert into Nation(CountryCode, CName, EName) values('LB', '黎巴嫩', 'LEBANON')
insert into Nation(CountryCode, CName, EName) values('LC', '聖盧西亞', 'ST LUCIA')
insert into Nation(CountryCode, CName, EName) values('LI', '列支敦斯登', 'LIECHTENSTEIN')
insert into Nation(CountryCode, CName, EName) values('LK', '斯里蘭卡', 'SRI LANKA')
insert into Nation(CountryCode, CName, EName) values('LR', '利比里亞', 'LIBERIA')
insert into Nation(CountryCode, CName, EName) values('LS', '萊索托', 'LESOTHO')
insert into Nation(CountryCode, CName, EName) values('LT', '立陶宛', 'LITHUANIA')
insert into Nation(CountryCode, CName, EName) values('LU', '盧森堡', 'LUXEMBOURG')
insert into Nation(CountryCode, CName, EName) values('LV', '拉脫維亞', 'LATVIA')
insert into Nation(CountryCode, CName, EName) values('LW', '背風群島', 'LEWARD ISLANDS')
insert into Nation(CountryCode, CName, EName) values('LY', '利比亞', 'LIBYA')
insert into Nation(CountryCode, CName, EName) values('MA', '摩洛哥', 'MOROCCO')
insert into Nation(CountryCode, CName, EName) values('MC', '摩納哥', 'MONACO')
insert into Nation(CountryCode, CName, EName) values('MD', '摩爾多瓦共和國', 'MOLDOVA REP')
insert into Nation(CountryCode, CName, EName) values('ME', '蒙特內哥羅', 'MONTENEGRO')
insert into Nation(CountryCode, CName, EName) values('MG', '馬達加斯加', 'MADAGASCAR')
insert into Nation(CountryCode, CName, EName) values('MH', '馬紹爾群島', 'MARSHALL ISLANDS')
insert into Nation(CountryCode, CName, EName) values('MI', '中途島', 'MIDWAY')
insert into Nation(CountryCode, CName, EName) values('MK', '馬其頓', 'MACEDONIA')
insert into Nation(CountryCode, CName, EName) values('ML', '馬雷', 'MALI')
insert into Nation(CountryCode, CName, EName) values('MM', '緬甸', 'MYANMAR')
insert into Nation(CountryCode, CName, EName) values('MN', '蒙古', 'MONGOLIA')
insert into Nation(CountryCode, CName, EName) values('MO', '澳門', 'MACAU')
insert into Nation(CountryCode, CName, EName) values('MP', '北馬里亞納群島', 'NORTHERN MARIANA ISLANDS')
insert into Nation(CountryCode, CName, EName) values('MQ', '馬丁尼克島', 'MARTINIQUE')
insert into Nation(CountryCode, CName, EName) values('MR', '毛里塔尼亞', 'MAURITANIA')
insert into Nation(CountryCode, CName, EName) values('MS', '蒙瑟拉特島', 'MONTSERRAT')
insert into Nation(CountryCode, CName, EName) values('MT', '馬爾他', 'MALTA')
insert into Nation(CountryCode, CName, EName) values('MU', '毛里求斯', 'MAURITIUS')
insert into Nation(CountryCode, CName, EName) values('MV', '馬爾代夫', 'MALDIVES')
insert into Nation(CountryCode, CName, EName) values('MW', '馬拉維', 'MALAWI')
insert into Nation(CountryCode, CName, EName) values('MX', '墨西哥', 'MEXICO')
insert into Nation(CountryCode, CName, EName) values('MY', '馬來西亞', 'MALAYSIA')
insert into Nation(CountryCode, CName, EName) values('MZ', '莫桑比克', 'MOZAMBIQUE')
insert into Nation(CountryCode, CName, EName) values('NA', '納米比亞', 'NAMIBIA')
insert into Nation(CountryCode, CName, EName) values('NC', '法屬新喀里多尼亞島', 'NEW CALEDONIA')
insert into Nation(CountryCode, CName, EName) values('NE', '尼日爾', 'NIGER')
insert into Nation(CountryCode, CName, EName) values('NF', '諾福克群島', 'NORFOLK ISLAND')
insert into Nation(CountryCode, CName, EName) values('NG', '尼日利亞', 'NIGERIA')
insert into Nation(CountryCode, CName, EName) values('NI', '尼加拉瓜', 'NICARAGUA')
insert into Nation(CountryCode, CName, EName) values('NL', '荷蘭', 'NETHERLANDS')
insert into Nation(CountryCode, CName, EName) values('NO', '挪威', 'NORWAY')
insert into Nation(CountryCode, CName, EName) values('NP', '尼泊爾', 'NEPAL')
insert into Nation(CountryCode, CName, EName) values('NQ', '聖德女王領地', 'DRONNING MAUD LAND')
insert into Nation(CountryCode, CName, EName) values('NR', '瑙魯', 'NAURU')
insert into Nation(CountryCode, CName, EName) values('NU', '紐埃', 'NIUE')
insert into Nation(CountryCode, CName, EName) values('NZ', '新西蘭', 'NEW ZEALAND')
insert into Nation(CountryCode, CName, EName) values('OM', '阿曼', 'OMAN')
insert into Nation(CountryCode, CName, EName) values('PA', '巴拿馬', 'PANAMA')
insert into Nation(CountryCode, CName, EName) values('PC', '美國太平洋島嶼', 'US PACIFIC IS')
insert into Nation(CountryCode, CName, EName) values('PE', '秘魯', 'PERU')
insert into Nation(CountryCode, CName, EName) values('PF', '法屬玻里尼西亞', 'FRENCH POLYNESI')
insert into Nation(CountryCode, CName, EName) values('PG', '巴布亞新幾內亞', 'PAPUA NEW GUINE')
insert into Nation(CountryCode, CName, EName) values('PH', '菲律賓', 'PHILIPPINES')
insert into Nation(CountryCode, CName, EName) values('PK', '巴基斯坦', 'PAKISTAN')
insert into Nation(CountryCode, CName, EName) values('PL', '波蘭', 'POLAND')
insert into Nation(CountryCode, CName, EName) values('PM', '聖匹爾及密啟倫群島', 'ST PIERRE MIQUELON')
insert into Nation(CountryCode, CName, EName) values('PN', '皮特克恩群島', 'PITCAIRN ISLAND')
insert into Nation(CountryCode, CName, EName) values('PO', '梵諦岡', 'VATICAN CITY')
insert into Nation(CountryCode, CName, EName) values('PR', '波多黎各', 'PUERTO RICO')
insert into Nation(CountryCode, CName, EName) values('PS', '巴勒斯坦佔領區', 'OCCUPIED PALESTINIAN TERR')
insert into Nation(CountryCode, CName, EName) values('PT', '葡萄牙', 'PORTUGAL')
insert into Nation(CountryCode, CName, EName) values('PW', 'PALAU', 'PALAU')
insert into Nation(CountryCode, CName, EName) values('PY', '巴拉圭', 'PARAGUAY')
insert into Nation(CountryCode, CName, EName) values('PZ', '巴拿馬運河區', 'PANAMA CANAL ZONE')
insert into Nation(CountryCode, CName, EName) values('QA', '卡塔爾', 'QATAR')
insert into Nation(CountryCode, CName, EName) values('RE', '留尼旺', 'REUNION')
insert into Nation(CountryCode, CName, EName) values('RO', '羅馬尼亞', 'ROMANIA')
insert into Nation(CountryCode, CName, EName) values('RS', 'SERBIA', 'SERBIA')
insert into Nation(CountryCode, CName, EName) values('RU', '俄羅斯', 'RUSSIA')
insert into Nation(CountryCode, CName, EName) values('RW', '盧旺達', 'RWANDA')
insert into Nation(CountryCode, CName, EName) values('SA', '沙烏地阿拉伯', 'SAUDI ARABIA')
insert into Nation(CountryCode, CName, EName) values('SB', '索羅門群島', 'SOLOMON ISLANDS')
insert into Nation(CountryCode, CName, EName) values('SC', '塞舌爾', 'SEYCHELLES')
insert into Nation(CountryCode, CName, EName) values('SD', '蘇丹', 'SUDAN')
insert into Nation(CountryCode, CName, EName) values('SE', '瑞典', 'SWEDEN')
insert into Nation(CountryCode, CName, EName) values('SG', '新加坡', 'SINGAPORE')
insert into Nation(CountryCode, CName, EName) values('SH', '聖赫勒拿', 'ST HELENA')
insert into Nation(CountryCode, CName, EName) values('SI', '斯洛維尼亞', 'SLOVENIA')
insert into Nation(CountryCode, CName, EName) values('SJ', '斯瓦巴及尖棉島', 'SVALBARD JAN MAYAN IS')
insert into Nation(CountryCode, CName, EName) values('SK', '斯洛伐克', 'SLOVAKIA')
insert into Nation(CountryCode, CName, EName) values('SL', '獅子山', 'SIERRA LEONE')
insert into Nation(CountryCode, CName, EName) values('SM', '聖馬力諾', 'SAN MARINO')
insert into Nation(CountryCode, CName, EName) values('SN', '塞內加爾', 'SENEGAL')
insert into Nation(CountryCode, CName, EName) values('SO', '索馬利亞', 'SOMALIA')
insert into Nation(CountryCode, CName, EName) values('SR', '蘇利南', 'SURINAME')
insert into Nation(CountryCode, CName, EName) values('ST', '聖多美及普林西比', 'SAO TOME AND PR')
insert into Nation(CountryCode, CName, EName) values('SV', '薩爾瓦多', 'EL SALVADOR')
insert into Nation(CountryCode, CName, EName) values('SY', '敘利亞', 'SYRIA')
insert into Nation(CountryCode, CName, EName) values('SZ', '史瓦濟蘭', 'SWAZILAND')
insert into Nation(CountryCode, CName, EName) values('TC', '土克斯及開科斯群島', 'TURKS AND CAICOS IS')
insert into Nation(CountryCode, CName, EName) values('TD', '查德', 'CHAD')
insert into Nation(CountryCode, CName, EName) values('TG', '多哥', 'TOGO')
insert into Nation(CountryCode, CName, EName) values('TH', '泰國', 'THAILAND')
insert into Nation(CountryCode, CName, EName) values('TJ', '塔吉克', 'TAJIKISTAN')
insert into Nation(CountryCode, CName, EName) values('TK', '托克勞群島', 'TOKELAU')
insert into Nation(CountryCode, CName, EName) values('TM', '土庫曼', 'TURKMENISTAN')
insert into Nation(CountryCode, CName, EName) values('TN', '突尼西亞', 'TUNISIA')
insert into Nation(CountryCode, CName, EName) values('TO', '東加', 'TONGA')
insert into Nation(CountryCode, CName, EName) values('TR', '土耳其', 'TURKEY')
insert into Nation(CountryCode, CName, EName) values('TT', '千里達', 'TRINIDAD')
insert into Nation(CountryCode, CName, EName) values('TV', '吐瓦魯', 'TUVALU')
insert into Nation(CountryCode, CName, EName) values('TW', '臺灣', 'TAIWAN')
insert into Nation(CountryCode, CName, EName) values('TZ', '坦尚尼亞', 'TANZANIA')
insert into Nation(CountryCode, CName, EName) values('UA', '烏克蘭', 'UKRAINE')
insert into Nation(CountryCode, CName, EName) values('UG', '烏干達', 'UGANDA')
insert into Nation(CountryCode, CName, EName) values('US', '美國', 'UNITED STATES')
insert into Nation(CountryCode, CName, EName) values('UY', '烏拉圭', 'URUGUAY')
insert into Nation(CountryCode, CName, EName) values('UZ', '烏茲別克', 'UZBEKISTAN')
insert into Nation(CountryCode, CName, EName) values('VA', '梵蒂岡', 'VATICAN CITY STATE')
insert into Nation(CountryCode, CName, EName) values('VC', '聖文森', 'ST VINCENT')
insert into Nation(CountryCode, CName, EName) values('VE', '委內瑞拉', 'VENEZUELA')
insert into Nation(CountryCode, CName, EName) values('VG', '英屬維爾京群島', 'BRITISH VIRGIN')
insert into Nation(CountryCode, CName, EName) values('VI', '美屬維爾京群島', 'VIRGIN ISLANDS')
insert into Nation(CountryCode, CName, EName) values('VN', '越南', 'VIETNAM')
insert into Nation(CountryCode, CName, EName) values('VU', '瓦努阿圖', 'VANUATU')
insert into Nation(CountryCode, CName, EName) values('WF', '沃里斯與伏塔那島', 'WALLIS FUTUNA ISLANDS')
insert into Nation(CountryCode, CName, EName) values('WK', '威克島', 'WAKE ISLAND')
insert into Nation(CountryCode, CName, EName) values('WS', '薩摩亞', 'WESTERN SAMOA')
insert into Nation(CountryCode, CName, EName) values('WW', '向風群島', 'WINDWARD IS')
insert into Nation(CountryCode, CName, EName) values('XE', '烏茲別克', 'UZ HIDDEN')
insert into Nation(CountryCode, CName, EName) values('XU', '東烏拉爾（俄羅斯）', 'E URAL RUSSIA')
insert into Nation(CountryCode, CName, EName) values('YE', '葉門共和國', 'YEMEN REPUBLIC')
insert into Nation(CountryCode, CName, EName) values('YT', '馬亞特島', 'MAYOTTE')
insert into Nation(CountryCode, CName, EName) values('YU', '塞爾維亞', 'YUGOSLAVIA')
insert into Nation(CountryCode, CName, EName) values('ZA', '南非', 'SOUTH AFRICA')
insert into Nation(CountryCode, CName, EName) values('ZM', '尚比亞', 'ZAMBIA')
insert into Nation(CountryCode, CName, EName) values('ZU', '格林威治英國', 'GREENWICH ENGLAND')
insert into Nation(CountryCode, CName, EName) values('ZW', '辛巴威', 'ZIMBABWE')

